# Generated by Django 4.1.5 on 2023-03-30 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('tur', models.CharField(blank=True, max_length=50)),
                ('manzil', models.CharField(blank=True, max_length=50)),
                ('ism', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('brend', models.CharField(blank=True, max_length=50)),
                ('miqdor', models.PositiveIntegerField()),
                ('narx', models.PositiveIntegerField()),
                ('olchov', models.CharField(max_length=30)),
                ('kelgan_sana', models.DateTimeField(auto_now_add=True)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlari', to='asosiy.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('manzil', models.CharField(blank=True, max_length=50)),
                ('ism', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=14)),
                ('qarz', models.PositiveIntegerField(default=0)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientlari', to='asosiy.ombor')),
            ],
        ),
    ]
